---

- name: Install Apache
  hosts: myservers
  # become: true
  # remote_user: root
  
  tasks:
  
  # Installing Apache Server
  - name: Install Apache
    yum:
      name: httpd
      state: present
  
  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes


  # Installing Docker
  - name: "Installing Docker Prerequisite packages"
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

  - name: "Configuring docker-ce repo"
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
  
  - name: " Installing Docker latest version"
    yum:
      name: docker-ce
      state: present
    
  - name: " Starting and Enabling Docker service"
    service:
      name: docker
      state: started
      enabled: yes


  # Configuration DNS
  - name: Make sure some records exist and have the expected values
    community.dns.hosttech_dns_record_sets:
      zone_name: foo.com
      records:
        - prefix: new
          type: A
          ttl: 7200
          value:
            - 1.1.1.1
            - 2.2.2.2
        - prefix: new
          type: AAAA
          ttl: 7200
          value:
            - "::1"
        - record: foo.com
          type: TXT
          value:
            - test
      hosttech_username: "root"
      hosttech_password: "$3Rv3R0n3Hom3"

  - name: Synchronize DNS zone with a fixed set of records
    # If a record exists that is not mentioned here, it will be deleted
    community.dns.hosttech_dns_record_sets:
      zone_id: 23
      purge: true
      records:
        - prefix: ''
          type: A
          value: 127.0.0.1
        - prefix: ''
          type: AAAA
          value: "::1"
        - prefix: ''
          type: NS
          value:
            - ns-1.hoster.com
            - ns-2.hoster.com
            - ns-3.hoster.com
      hosttech_username: "root"
      hosttech_password: "$3Rv3R0n3Hom3"

